### ISSUE TITLE
remark-rehype strips out <figure>

### ISSUE THREAD

**Issue by johnston** [florianeckerstorfer/remark-images#7]
Inside `eleventy-plugin-remark`, `remark-rehype` strips out the `<figure>` tag unless you tell it to `allowDangerousHtml: true` and then use `rehype-raw` before `rehype-stringify`.

(There is a helpful comment at the top of https://github.com/remarkjs/remark-rehype which pointed me towards rehype-raw.

So this works:

```js
eleventyConfig.addPlugin(eleventyRemark, {
    plugins: [{
      plugin: remarkImages,
      options: {
        srcDir: path.join(__dirname,'src'),
        targetDir: path.join(__dirname, 'dist'),
      },
    }, {
      plugin: remarkRehype,
      options: {
        allowDangerousHtml: true
      }
    }, 
    rehypeRaw,
    rehypeStringify
    ],
  });
```

but you need to comment out `remarkRehype` and `rehypeStringify` in https://github.com/florianeckerstorfer/eleventy-plugin-remark/blob/917ce1d6ed3bbd1ea413c047debe52848bfa6f55/src/eleventyRemark.js#L41:

```js
function eleventyRemark(options) {
  const processor = remark();
  let plugins = requirePlugins(options.plugins);
  processor.use(plugins) // .use(remarkRehype).use(rehypeStringify);
```

but I assume that breaks the plugin, so you could also allow the raw html directly in `eleventy-plugin-remark`

```js
function eleventyRemark(options) {
  const processor = remark();
  let plugins = requirePlugins(options.plugins);
  processor.use(plugins).use(remarkRehype, {allowDangerousHtml:true).use(rehypeRaw).use(rehypeStringify);
```

but that maybe sets a dangerous precedent allowing the raw HTML through.

Not quite sure what the next steps would be to make it work?

**Comment by florianeckerstorfer** [comment]
Thanks for the issue and the investigation, I was struggling with this recently as well, but didn't find the time to investigate further. What do you think about adding an option do disable the auto-rehype+stringify plugins?

```javascript
eleventyConfig.addPlugin(eleventyRemark, {
    rehypeStringify: false, // defaults to `true` for backwards compatibility
    plugins: [{
      plugin: remarkImages,
      options: {
        srcDir: path.join(__dirname,'src'),
        targetDir: path.join(__dirname, 'dist'),
      },
    }, {
      plugin: remarkRehype,
      options: {
        allowDangerousHtml: true
      }
    }, 
    rehypeRaw,
    rehypeStringify
    ],
  });
```

I could probably create a PR on the weekend.

**Comment by johnston** [comment]
@florianeckerstorfer Perhaps naming it something like `enableRehype` would be clearer on the basis that we have to turn off `remark-rehype` and also `rehype-stringify` before adding them back in with `allowDangerousHtml` and `rehype-raw` in the mix.

But - yes, that would solve it!

**Comment by florianeckerstorfer** [comment]
@johnston You're right, `enableRehype` is a better name and I think also ensures that people who don't know anything about rehype keep the fingers off it. I've created a PR for `eleventy-plugin-remark`, it would be great if you could take a look if this would solve this issue for you.

**Comment by johnston** [comment]
@florianeckerstorfer Yes - that works great. Have tested it and runs as expected.

Thanks!

**Comment by florianeckerstorfer** [comment]
@johnston Merged florianeckerstorfer/eleventy-plugin-remark#59 and I will publish a release after work today.

**Comment by florianeckerstorfer** [comment]
@johnston florianeckerstorfer/eleventy-plugin-remark v2.2.1 has been published. Thanks for the issue and the investigation.

**Comment by johnston** [comment]
@florianeckerstorfer excellent. The extension is excellent btw. I looked at a few but this was by far the most comprehensive and easy to use.
